# source this to pick up the right shell context

INSTALL_DIR=$(dirname -- "$(readlink -f -- "$0")")

set_up_config() {
  local dir="$1"

  VRC_SRC="${INSTALL_DIR}/config/${dir}"
  VRC_DEST_STR="${HOME}/.config/${dir}"
  # -e[ither] -f[ile] or -d[irectory] exists
  if [[ ! -e "${VRC_DEST_STR}" ]]; then
    ln -s "${VRC_SRC}" "${VRC_DEST_STR}" 
    echo "linked ${VRC_SRC} to ${VRC_SRC}✅"
  else
    echo "$VRC_DEST_STR already exists, skipping. ❌"
  fi
}

# debug shell
# https://stackoverflow.com/questions/60844165/definitively-determine-if-currently-running-shell-is-bash-or-zsh
# shell_name="$(ps -o comm= -p $$)"
# echo "${shell_name##*[[:cntrl:][:punct:][:space:]]}"
mkdir -p "${HOME}/.config"
set_up_config tmux
set_up_config vim

# -n: if not null or empty
if [ -n "$ZSH_VERSION" ]; then
  echo "Detected Zsh."
  echo "appending bashrc to .zshrc"
  echo "source ${INSTALL_DIR}/config/bashrc" >> .zshrc
elif [ -n "$BASH_VERSION" ]; then
  echo "Detected Bash."
  echo "appending bashrc to .bashrc"
  echo "source ${INSTALL_DIR}/config/bashrc" >> .bashrc
else
  echo "Not sure how to set up this shell. ❌"
fi
echo "Set up complete! ✅"
